### ISSUE TITLE
MetaSys 13 API v5

### ISSUE THREAD

**Issue by DougPlumley** [jci-metasys/api-landing#113]
Hi,

It looks like there is a version 5 REST API available in MetaSys 13, could you please publish the documentation for the latest version?

**Comment by michaelgwelch** [comment]
PR for this is currently open

**Comment by michaelgwelch** [comment]
#115 has been merged and you'll see the v5 spec is now live

**Comment by DougPlumley** [comment]
Thank you @michaelgwelch!
